" ### ### ### CONFIGURACIÓN VIM ### ### ###
  source $HOME/.vim/settings/general_config.vim
  source $HOME/.vim/settings/keyborad.vim
  source $HOME/.vim/settings/plugins.vim
  source $HOME/.vim/settings/status_bar.vim
  source $HOME/.vim/settings/scheme_color.vim
  source $HOME/.vim/settings/setting_coc.vim


